### ISSUE TITLE
Data transfer

### ISSUE THREAD

**Issue by rlayte** [rlayte/toystore#10]
This shouldn't use standard coordination for two reasons:
- It's inefficient. We know we're sending a whole key range so sending each key as an individual rpc doesn't make use of this.
- Because coordinate sends replication requests to n adjacent hosts it will send it on to hosts that already have the data.

We should create a new transfer RPC handler instead.

**Comment by charlesetc** [comment]
Good call, on both parts. I'll take care of it.

**Comment by charlesetc** [comment]
Should be done with the Hinted Handoff rpc instead of the current one.
